// This file is part of midnightntwrk/example-secretbid.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * This file is the main driver for the Midnight secret bid example.
 * The entry point is the run function, at the end of the file.
 * We expect the startup files (testnet-remote.ts, standalone.ts, etc.) to
 * call run with some specific configuration that sets the network addresses
 * of the servers this file relies on.
 */

import { createInterface, type Interface } from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import { WebSocket } from 'ws';
import {
  SecretBidAPI,
  type AuctionDerivedState,
  type AuctionId,
  secretBidPrivateStateKey,
  type SecretBidProviders,
  type DeployedSecretBidContract,
  type PrivateStateId,
} from '../../api/src/index';
import { type WalletFacade } from '@midnight-ntwrk/wallet-sdk-facade';
import { ledger, type Ledger } from '../../contract/src/managed/secretbid/contract/index.js';
import { NodeZkConfigProvider } from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { type Logger } from 'pino';
import { type Config, StandaloneConfig } from './config.js';
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import { type ContractAddress } from '@midnight-ntwrk/midnight-js-protocol/compact-runtime';
import { assertIsContractAddress, toHex } from '@midnight-ntwrk/midnight-js-utils';
import { TestEnvironment } from '@midnight-ntwrk/testkit-js';
import { MidnightWalletProvider } from './midnight-wallet-provider';
import { randomBytes } from '../../api/src/utils';
import { unshieldedToken } from '@midnight-ntwrk/midnight-js-protocol/ledger';
import { syncWallet, waitForUnshieldedFunds } from './wallet-utils';
import { generateDust } from './generate-dust';
import { SecretBidPrivateState } from '../../contract/src/witnesses.js';

// @ts-expect-error: It's needed to enable WebSocket usage through apollo
globalThis.WebSocket = WebSocket;

/* **********************************************************************
 * getSecretBidLedgerState: a helper that queries the current state of
 * the data on the ledger, for a specific secret bid contract.
 * Note that the Ledger type returned here is not some generic,
 * abstract ledger object, but specifically the type generated by
 * the Compact compiler to correspond to the ledger declaration
 * in the secret bid contract.
 */

export const getSecretBidLedgerState = async (
  providers: SecretBidProviders,
  contractAddress: ContractAddress,
): Promise<Ledger | null> => {
  assertIsContractAddress(contractAddress);
  const contractState = await providers.publicDataProvider.queryContractState(contractAddress);
  return contractState != null ? ledger(contractState.data) : null;
};
// providers.publicDataProvider
//   .queryContractState(contractAddress)
//   .then((contractState) => (contractState != null ? ledger(contractState.data) : null));

/* **********************************************************************
 * deployOrJoin: returns a contract, by prompting the user about
 * whether to deploy a new one or join an existing one and then
 * calling the appropriate helper.
 */

const DEPLOY_OR_JOIN_QUESTION = `
You can do one of the following:
  1. Deploy a new secret bid contract
  2. Join an existing secret bid contract
  3. Exit
Which would you like to do? `;

const deployOrJoin = async (
  providers: SecretBidProviders,
  rli: Interface,
  logger: Logger,
): Promise<SecretBidAPI | null> => {
  let api: SecretBidAPI | null = null;

  while (true) {
    const choice = await rli.question(DEPLOY_OR_JOIN_QUESTION);
    switch (choice) {
      case '1':
        api = await SecretBidAPI.deploy(providers, logger);
        logger.info(`Deployed contract at address: ${api.deployedContractAddress}`);
        return api;
      case '2':
        api = await SecretBidAPI.join(providers, await rli.question('What is the contract address (in hex)? '), logger);
        logger.info(`Joined contract at address: ${api.deployedContractAddress}`);
        return api;
      case '3':
        logger.info('Exiting...');
        return null;
      default:
        logger.error(`Invalid choice: ${choice}`);
    }
  }
};

/* **********************************************************************
 * displayLedgerState: shows the raw ledger fields (auctionCount, and the
 * number of auctions/commitments/reveals known so far) for the connected
 * secret bid contract.
 */

const displayLedgerState = async (
  providers: SecretBidProviders,
  deployedSecretBidContract: DeployedSecretBidContract,
  logger: Logger,
): Promise<void> => {
  const contractAddress = deployedSecretBidContract.deployTxData.public.contractAddress;
  const ledgerState = await getSecretBidLedgerState(providers, contractAddress);
  if (ledgerState === null) {
    logger.info(`There is no secret bid contract deployed at ${contractAddress}`);
  } else {
    logger.info(`Total auctions created: ${ledgerState.auctionCount}`);
    logger.info(`Auctions on ledger: ${ledgerState.auctions.size()}`);
    logger.info(`Commitments on ledger: ${ledgerState.commitments.size()}`);
    logger.info(`Revealed bids on ledger: ${ledgerState.revealedBids.size()}`);
  }
};

/* **********************************************************************
 * displayPrivateState: shows the hex-formatted secret key and the
 * auctionIds this DApp instance has locally prepared a bid secret for.
 */

const displayPrivateState = async (providers: SecretBidProviders, logger: Logger): Promise<void> => {
  const privateState = await providers.privateStateProvider.get(secretBidPrivateStateKey);
  if (privateState === null) {
    logger.info(`There is no existing secret bid private state`);
  } else {
    logger.info(`Current secret key is: ${toHex(privateState.secretKey)}`);
    const auctionIds = Object.keys(privateState.bids);
    logger.info(
      auctionIds.length ? `Locally prepared bids for auctions: ${auctionIds.join(', ')}` : 'No locally prepared bids',
    );
  }
};

/* **********************************************************************
 * displayAuctionList: shows every auction currently known to this
 * contract, from the latest `auctions$` snapshot.
 */

const displayAuctionList = (auctions: ReadonlyMap<AuctionId, AuctionDerivedState>, logger: Logger): void => {
  if (auctions.size === 0) {
    logger.info('No auctions created yet');
    return;
  }
  for (const auction of auctions.values()) {
    logger.info(
      `${auction.auctionId} — "${auction.title}" [${auction.phase}] commits=${auction.commitCount} reveals=${auction.revealCount}`,
    );
  }
};

/* **********************************************************************
 * displayAuctionDerivedState: shows the derived state of a single
 * auction, combining its public ledger record with this DApp instance's
 * own private state (never another bidder's).
 */

const displayAuctionDerivedState = (auction: AuctionDerivedState | undefined, logger: Logger): void => {
  if (auction === undefined) {
    logger.info('No such auction is currently known');
    return;
  }
  logger.info(`Auction: '${auction.title}' (${auction.auctionId})`);
  logger.info(`  Description: ${auction.description}`);
  logger.info(`  Phase: ${auction.phase}`);
  logger.info(`  Reserve price: ${auction.reservePrice ?? 'none'}`);
  logger.info(`  Commits: ${auction.commitCount}, Reveals: ${auction.revealCount}`);
  logger.info(`  Winner: ${auction.winner ?? 'none yet'}, Winning bid: ${auction.winningBid ?? 'none yet'}`);
  logger.info(
    `  You: creator=${auction.isCreator}, committed=${auction.hasCommitted}, revealed=${auction.hasRevealed}, winner=${auction.isWinner}`,
  );
};

/* **********************************************************************
 * auctionLoop: the per-auction interactive menu of the secret bid CLI.
 * Reached after selecting or creating an auction from the main loop.
 */

const AUCTION_LOOP_QUESTION = `
You can do one of the following:
  1. Commit a bid
  2. Start the reveal phase (creator only)
  3. Reveal my bid
  4. Close the auction (creator only)
  5. Display this auction's state
  6. Back to the auction list
Which would you like to do? `;

const auctionLoop = async (
  secretBidApi: SecretBidAPI,
  auctionId: AuctionId,
  rli: Interface,
  logger: Logger,
): Promise<void> => {
  while (true) {
    const choice = await rli.question(AUCTION_LOOP_QUESTION);
    try {
      switch (choice) {
        case '1': {
          const amount = BigInt(await rli.question('What is your bid amount? '));
          await secretBidApi.commitBid(auctionId, amount);
          break;
        }
        case '2':
          await secretBidApi.startReveal(auctionId);
          break;
        case '3':
          await secretBidApi.revealBid(auctionId);
          break;
        case '4':
          await secretBidApi.closeAuction(auctionId);
          break;
        case '5':
          displayAuctionDerivedState(secretBidApi.getAuction(auctionId), logger);
          break;
        case '6':
          return;
        default:
          logger.error(`Invalid choice: ${choice}`);
      }
    } catch (e) {
      logError(logger, e);
      logger.info('Returning to auction menu...');
    }
  }
};

/* **********************************************************************
 * mainLoop: the main interactive menu of the secret bid CLI.
 * Before starting the loop, the user is prompted to deploy a new
 * contract or join an existing one — that contract is the "auction
 * house" this loop then creates and interacts with auctions on.
 */

const MAIN_LOOP_QUESTION = `
You can do one of the following:
  1. Create a new auction
  2. List all known auctions
  3. Select an auction to interact with
  4. Display the current ledger state (known by everyone)
  5. Display the current private state (known only to this DApp instance)
  6. Exit
Which would you like to do? `;

const mainLoop = async (providers: SecretBidProviders, rli: Interface, logger: Logger): Promise<void> => {
  const secretBidApi = await deployOrJoin(providers, rli, logger);
  if (secretBidApi === null) {
    return;
  }
  let currentAuctions: ReadonlyMap<AuctionId, AuctionDerivedState> = new Map();
  const subscription = secretBidApi.auctions$.subscribe((auctions) => (currentAuctions = auctions));
  try {
    while (true) {
      const choice = await rli.question(MAIN_LOOP_QUESTION);
      try {
        switch (choice) {
          case '1': {
            const title = await rli.question('Auction title? ');
            const description = await rli.question('Auction description? ');
            const reserveInput = await rli.question('Reserve price (blank for none)? ');
            const auctionId = await secretBidApi.createAuction({
              title,
              description,
              reservePrice: reserveInput.length ? BigInt(reserveInput) : undefined,
            });
            logger.info(`Created auction: ${auctionId}`);
            break;
          }
          case '2':
            displayAuctionList(currentAuctions, logger);
            break;
          case '3': {
            const auctionId = await rli.question('Auction id (in hex)? ');
            await auctionLoop(secretBidApi, auctionId, rli, logger);
            break;
          }
          case '4':
            await displayLedgerState(providers, secretBidApi.deployedContract, logger);
            break;
          case '5':
            await displayPrivateState(providers, logger);
            break;
          case '6':
            logger.info('Exiting...');
            return;
          default:
            logger.error(`Invalid choice: ${choice}`);
        }
      } catch (e) {
        logError(logger, e);
        logger.info('Returning to main menu...');
      }
    }
  } finally {
    // While we allow errors to bubble up to the 'run' function, we will always need to dispose of the state
    // subscription when we exit.
    subscription.unsubscribe();
  }
};

/* ***********************************************************************
 * This seed gives access to tokens minted in the genesis block of a local development node - only
 * used in standalone networks to build a wallet with initial funds.
 */
const GENESIS_MINT_WALLET_SEED = '0000000000000000000000000000000000000000000000000000000000000001';

/* **********************************************************************
 * buildWallet: unless running in a standalone (offline) mode,
 * prompt the user to tell us whether to create a new wallet
 * or recreate one from a prior seed.
 */

const WALLET_LOOP_QUESTION = `
You can do one of the following:
  1. Build a fresh wallet
  2. Build wallet from a seed
  3. Exit
Which would you like to do? `;

const buildWallet = async (config: Config, rli: Interface, logger: Logger): Promise<string | undefined> => {
  if (config instanceof StandaloneConfig) {
    return GENESIS_MINT_WALLET_SEED;
  }
  while (true) {
    const choice = await rli.question(WALLET_LOOP_QUESTION);
    switch (choice) {
      case '1':
        return toHex(randomBytes(32));
      case '2':
        return await rli.question('Enter your wallet seed: ');
      case '3':
        logger.info('Exiting...');
        return undefined;
      default:
        logger.error(`Invalid choice: ${choice}`);
    }
  }
};

/* **********************************************************************
 * run: the main entry point that starts the whole secret bid CLI.
 *
 * If called with a Docker environment argument, the application
 * will wait for Docker to be ready before doing anything else.
 */

export const run = async (config: Config, testEnv: TestEnvironment, logger: Logger): Promise<void> => {
  const rli = createInterface({ input, output, terminal: true });
  const providersToBeStopped: MidnightWalletProvider[] = [];
  try {
    const envConfiguration = await testEnv.start();
    logger.info(`Environment started with configuration: ${JSON.stringify(envConfiguration)}`);
    const seed = await buildWallet(config, rli, logger);
    if (seed === undefined) {
      return;
    }
    const walletProvider = await MidnightWalletProvider.build(logger, envConfiguration, seed);
    providersToBeStopped.push(walletProvider);
    const walletFacade: WalletFacade = walletProvider.wallet;

    await walletProvider.start();

    const unshieldedState = await waitForUnshieldedFunds(logger, walletFacade, envConfiguration, unshieldedToken());
    const nightBalance = unshieldedState.balances[unshieldedToken().raw];
    if (nightBalance === undefined) {
      logger.info('No funds received, exiting...');
      return;
    }
    logger.info(`Your NIGHT wallet balance is: ${nightBalance}`);

    if (config.generateDust) {
      const dustGeneration = await generateDust(logger, seed, unshieldedState, walletFacade);
      if (dustGeneration) {
        logger.info(`Submitted dust generation registration transaction: ${dustGeneration}`);
        await syncWallet(logger, walletFacade);
      }
    }

    const zkConfigProvider = new NodeZkConfigProvider<
      'createAuction' | 'commitBid' | 'startReveal' | 'revealBid' | 'closeAuction'
    >(config.zkConfigPath);
    const providers: SecretBidProviders = {
      privateStateProvider: levelPrivateStateProvider<PrivateStateId, SecretBidPrivateState>({
        privateStateStoreName: config.privateStateStoreName,
        signingKeyStoreName: `${config.privateStateStoreName}-signing-keys`,
        privateStoragePasswordProvider: () => {
          return 'Secretbid-Test-2026!';
        },
        accountId: seed,
      }),
      publicDataProvider: indexerPublicDataProvider(envConfiguration.indexer, envConfiguration.indexerWS),
      zkConfigProvider: zkConfigProvider,
      proofProvider: httpClientProofProvider(envConfiguration.proofServer, zkConfigProvider),
      walletProvider: walletProvider,
      midnightProvider: walletProvider,
    };
    await mainLoop(providers, rli, logger);
  } catch (e) {
    logError(logger, e);
    logger.info('Exiting...');
  } finally {
    try {
      rli.close();
      rli.removeAllListeners();
    } catch (e) {
      logError(logger, e);
    } finally {
      try {
        for (const wallet of providersToBeStopped) {
          logger.info('Stopping wallet...');
          await wallet.stop();
        }
        if (testEnv) {
          logger.info('Stopping test environment...');
          await testEnv.shutdown();
        }
      } catch (e) {
        logError(logger, e);
      }
    }
  }
};

function logError(logger: Logger, e: unknown) {
  if (e instanceof Error) {
    logger.error(`Found error '${e.message}'`);
    logger.debug(`${e.stack}`);
  } else {
    logger.error(`Found error (unknown type)`);
  }
}
